"use client";
import "./global.scss";
import { Inter } from "next/font/google";
import { ScoreContextProvider } from "@/contexts/ScoreContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ScoreContextProvider>
        <body className={inter.className}>{children}</body>
      </ScoreContextProvider>
    </html>
  );
}
